name: todo_sqflite
description: "Todo app using SQLite"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^3.1.0
  flutter_hooks: ^0.21.3
  dart_flutter_common:
    path: ../dart_flutter_common
  go_router: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true
